version: 0.1.{build}
image: Visual Studio 2017
configuration: Release

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

before_build:
  - ps: Scripts\SetPathToProject.ps1

build:
  project: EmacsLikeKeyBindingsFDPlugin.sln
  verbosity: minimal

after_build:
  - ps: Scripts\ArchiveBuildResult.ps1

artifacts:
  - path: lpubsppop01.EmacsLikeKeyBindingsFDPlugin.fdz